#from .help import help
from .millo import millo
from .ping import ping
#from .player import play
from .roll import roll
#from .rougen import rougen
#from .serverinfo import serverinfo
#from .switch import switch
from .ip import ip
from .test import test